name: 'Release'
on:
  release:
    # runs for stable and pre-releases
    types: [published]

permissions:
  contents: read

jobs:
  cancel-previous-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write # for cancel-workflow-action
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@3155a141048f8f89c06b4cdae32e7853e97536bc # pin@0.13.0
        with:
          access_token: ${{ github.token }}

  release:
    name: Release
    runs-on: macos-14
    env:
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }} # Using @ioannisj token 

    steps:
      - name: Git checkout
        uses: actions/checkout@v6
      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: '16.2'

      - name: Bootstrap
        run: make bootstrap

      - name: Release
        run: make releaseCocoaPods
